sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO="django >=1.8,<1.9"
    - DJANGO="django >=1.9,<1.10"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django >=1.9,<1.10"

before_install:
  - pip install --upgrade pip wheel

# install dependencies
install:
  - pip install "$DJANGO"
  - python setup.py install
  - pip install -r dev-requirements.txt

# lint before testing
before_script:
  - flake8 .

# run tests
script: ./manage.py test --with-coverage

# publish coverage reports
after_success:
  - coverage report
  - codecov

# Only send emails about failures
notifications:
  email:
    on_success: never
    on_failure: always