# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='An article title is restricted to 200 characters.', max_length=200, verbose_name='Article')),
                ('body', models.TextField(help_text='The body of an article can contain HTML as well as text.', verbose_name='Article Body Content')),
                ('time_published', models.DateTimeField(default=django.utils.timezone.now, help_text=('Please use the following format: ', '<em>YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]</em>'), verbose_name='Time Published')),
            ],
        ),
    ]
