# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text="A category's title is restricted to 200 characters.", max_length=200, verbose_name='Category Title')),
                ('parent', models.ForeignKey(blank=True, help_text='Categories can be nested as deep as you would like.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpcenter.Category', verbose_name='Parent Category')),
            ],
        ),
    ]
