# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0004_auto_20160607_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='time last modifed'),
        ),
    ]
