# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0006_auto_20160715_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='time last modifed'),
        ),
    ]
