# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0007_auto_20160715_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False, help_text='Marking an article as a draft will hide it from users.', verbose_name='article is a draft'),
        ),
    ]
